import { defineField, defineType } from 'sanity'
import { MapPin } from 'lucide-react'

export default defineType({
  name: 'unit',
  title: 'Unidade',
  type: 'document',
  icon: MapPin,
  groups: [
    { name: 'info', title: 'Informações Básicas', default: true },
    { name: 'contact', title: 'Contato & Localização' },
    { name: 'media', title: 'Fotos & Galeria' },
    { name: 'content', title: 'Conteúdo & FAQ' },
    { name: 'seo', title: 'SEO & Dados Estruturados' },
  ],
  fields: [
    defineField({
      name: 'name',
      title: 'Nome da Unidade',
      type: 'string',
      group: 'info',
      validation: (Rule) => Rule.required().min(3).max(100),
      description: 'Ex: Moinhos de Vento - Luciana de Abreu',
    }),
    defineField({
      name: 'slug',
      title: 'Slug (URL)',
      type: 'slug',
      group: 'info',
      options: {
        source: 'name',
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
      description: 'Gerado automaticamente a partir do nome',
    }),
    defineField({
      name: 'order',
      title: 'Ordem de Exibição',
      type: 'number',
      group: 'info',
      validation: (Rule) => Rule.required().min(0),
      description: 'Ordem de exibição no site (0 = primeiro)',
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      group: 'info',
      options: {
        list: [
          { title: 'Ativa', value: 'active' },
          { title: 'Em breve', value: 'coming-soon' },
          { title: 'Inativa', value: 'inactive' },
        ],
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
      initialValue: 'active',
    }),
    defineField({
      name: 'phone',
      title: 'Telefone',
      type: 'string',
      group: 'contact',
      validation: (Rule) =>
        Rule.required().regex(/^\(\d{2}\) \d{4,5}-\d{4}$/, 'Formato: (51) 3346-7620'),
      description: 'Formato: (51) 3346-7620',
    }),
    defineField({
      name: 'whatsapp',
      title: 'WhatsApp',
      type: 'string',
      group: 'contact',
      validation: (Rule) => Rule.required().regex(/^55\d{10,11}$/, 'Formato: 555133467620'),
      description: 'Formato: 555133467620 (somente números com DDI)',
    }),
    defineField({
      name: 'email',
      title: 'E-mail',
      type: 'string',
      group: 'contact',
      validation: (Rule) => Rule.email(),
      description: 'E-mail específico da unidade (opcional)',
    }),
    defineField({
      name: 'address',
      title: 'Endereço Completo',
      type: 'text',
      group: 'contact',
      rows: 2,
      validation: (Rule) => Rule.required(),
      description: 'Ex: Rua Luciana de Abreu, 151 - Moinhos de Vento, Porto Alegre - RS, 90570-060',
    }),
    defineField({
      name: 'neighborhood',
      title: 'Bairro',
      type: 'string',
      group: 'contact',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'postalCode',
      title: 'CEP',
      type: 'string',
      group: 'contact',
      validation: (Rule) => Rule.regex(/^\d{5}-\d{3}$/, 'Formato: 90570-060'),
      description: 'Formato: 90570-060',
    }),
    defineField({
      name: 'coordinates',
      title: 'Coordenadas (Google Maps)',
      type: 'object',
      group: 'contact',
      fields: [
        {
          name: 'lat',
          title: 'Latitude',
          type: 'number',
          validation: (Rule) => Rule.required().min(-90).max(90),
        },
        {
          name: 'lng',
          title: 'Longitude',
          type: 'number',
          validation: (Rule) => Rule.required().min(-180).max(180),
        },
      ],
      description: 'Clique com botão direito no Google Maps → copiar coordenadas',
    }),
    defineField({
      name: 'mapsUrl',
      title: 'Link do Google Maps',
      type: 'url',
      group: 'contact',
      description: 'URL completa do Google Maps para a unidade',
    }),
    defineField({
      name: 'hours',
      title: 'Horário de Atendimento/Visitas',
      type: 'string',
      group: 'contact',
      validation: (Rule) => Rule.required(),
      initialValue: 'Visitas diárias das 9h às 19h com agendamento prévio',
    }),
    defineField({
      name: 'googlePlaceId',
      title: 'Google Place ID',
      type: 'string',
      group: 'seo',
      description: 'Place ID do Google para exibição de reviews (formato: ChIJ...)',
    }),
    defineField({
      name: 'featuredImage',
      title: 'Imagem Destaque',
      type: 'image',
      group: 'media',
      options: { hotspot: true },
      validation: (Rule) => Rule.required(),
      description: 'Imagem principal da unidade (aparece nos cards)',
    }),
    defineField({
      name: 'photos',
      title: 'Galeria de Fotos',
      type: 'array',
      group: 'media',
      of: [
        {
          type: 'image',
          options: { hotspot: true },
          fields: [
            {
              name: 'caption',
              title: 'Legenda',
              type: 'string',
              description: 'Descrição da foto para acessibilidade',
            },
            {
              name: 'category',
              title: 'Categoria',
              type: 'string',
              options: {
                list: [
                  { title: 'Externa', value: 'external' },
                  { title: 'Recepção', value: 'reception' },
                  { title: 'Quartos', value: 'rooms' },
                  { title: 'Áreas Comuns', value: 'common-areas' },
                  { title: 'Jardim', value: 'garden' },
                  { title: 'Refeitório', value: 'dining' },
                  { title: 'Atividades', value: 'activities' },
                ],
              },
            },
          ],
        },
      ],
      validation: (Rule) => Rule.min(3).max(20),
      description: 'Fotos da estrutura da unidade (mínimo 3, máximo 20)',
    }),
    defineField({
      name: 'description',
      title: 'Descrição Curta',
      type: 'text',
      group: 'content',
      rows: 3,
      validation: (Rule) => Rule.required().min(100).max(300),
      description: 'Descrição resumida para SEO e cards (100-300 caracteres)',
    }),
    defineField({
      name: 'longDescription',
      title: 'Descrição Completa',
      type: 'array',
      group: 'content',
      of: [
        {
          type: 'block',
          styles: [
            { title: 'Normal', value: 'normal' },
            { title: 'H2', value: 'h2' },
            { title: 'H3', value: 'h3' },
          ],
          lists: [
            { title: 'Lista com marcadores', value: 'bullet' },
            { title: 'Lista numerada', value: 'number' },
          ],
          marks: {
            decorators: [
              { title: 'Negrito', value: 'strong' },
              { title: 'Itálico', value: 'em' },
            ],
          },
        },
      ],
      description: 'Conteúdo completo da página da unidade',
    }),
    defineField({
      name: 'features',
      title: 'Diferenciais da Unidade',
      type: 'array',
      group: 'content',
      of: [{ type: 'string' }],
      description: 'Lista de diferenciais (ex: Jardim central, Próximo ao Parcão)',
      validation: (Rule) => Rule.max(6),
    }),
    defineField({
      name: 'faq',
      title: 'Perguntas Frequentes (FAQ)',
      type: 'array',
      group: 'content',
      of: [
        {
          type: 'object',
          fields: [
            {
              name: 'question',
              title: 'Pergunta',
              type: 'string',
              validation: (Rule) => Rule.required(),
            },
            {
              name: 'answer',
              title: 'Resposta',
              type: 'text',
              rows: 3,
              validation: (Rule) => Rule.required(),
            },
          ],
          preview: {
            select: {
              title: 'question',
              subtitle: 'answer',
            },
          },
        },
      ],
      description: 'Perguntas e respostas específicas da unidade',
    }),
    defineField({
      name: 'services',
      title: 'Serviços Disponíveis',
      type: 'array',
      group: 'content',
      of: [{ type: 'reference', to: [{ type: 'service' }] }],
      description: 'Serviços oferecidos nesta unidade',
    }),
    defineField({
      name: 'team',
      title: 'Equipe',
      type: 'array',
      group: 'content',
      of: [{ type: 'reference', to: [{ type: 'teamMember' }] }],
      description: 'Membros da equipe desta unidade',
    }),
    defineField({
      name: 'seoTitle',
      title: 'Título SEO',
      type: 'string',
      group: 'seo',
      validation: (Rule) => Rule.max(60),
      description: 'Título para mecanismos de busca (max 60 caracteres). Se vazio, usa o nome da unidade.',
    }),
    defineField({
      name: 'seoDescription',
      title: 'Descrição SEO',
      type: 'text',
      group: 'seo',
      rows: 2,
      validation: (Rule) => Rule.max(160),
      description: 'Descrição para mecanismos de busca (max 160 caracteres). Se vazio, usa a descrição curta.',
    }),
    defineField({
      name: 'seoImage',
      title: 'Imagem de Compartilhamento (OG)',
      type: 'image',
      group: 'seo',
      options: { hotspot: true },
      description: 'Imagem para compartilhamento social (1200x630px recomendado). Se vazio, usa a imagem destaque.',
    }),
    defineField({
      name: 'seoKeywords',
      title: 'Palavras-chave SEO',
      type: 'array',
      group: 'seo',
      of: [{ type: 'string' }],
      options: {
        layout: 'tags',
      },
      validation: (Rule) => Rule.max(10),
      description: 'Palavras-chave para SEO (máximo 10)',
    }),
  ],
  preview: {
    select: {
      title: 'name',
      subtitle: 'address',
      media: 'featuredImage',
      status: 'status',
    },
    prepare({ title, subtitle, media, status }) {
      return {
        title,
        subtitle: `${status === 'active' ? '✅' : status === 'coming-soon' ? '🔜' : '❌'} ${subtitle}`,
        media,
      }
    },
  },
})
